# Default values for meep-rnis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 1
  port: 80
  protocol: TCP
  dependencies:
    system:
      {{- if not .IsMepService }}
      - kube-dns
      {{- end }}
    sandbox:

image:
  repository: meep-docker-registry:30001/meep-rnis
  tag: latest
  pullPolicy: Always
  env:
    MEAS_REP_UE_PERIODIC_TRIGGER_INTERVAL: 1s
    NR_MEAS_REP_UE_PERIODIC_TRIGGER_INTERVAL: 1s
    MEEP_SANDBOX_NAME: {{.SandboxName}}
    MEEP_HOST_URL: {{.HostUrl}}
    {{- if .IsMepService }}
    MEEP_MEP_NAME: {{.MepName}}
    {{- end }}
    {{- if eq .AppEnablement "local" }}
    MEEP_APP_ENABLEMENT: {{.MepName}}-meep-app-enablement
    {{- else if eq .AppEnablement "global" }}
    MEEP_APP_ENABLEMENT: meep-app-enablement
    {{- end }}
    {{- range .Env}}
    {{.}}
    {{- end}}

service:
  {{- if .IsMepService }}
  name: {{.MepName}}-meep-rnis
  {{- else }}
  name: meep-rnis
  {{- end }}
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - name: ''
      paths:
        {{- if .IsMepService }}
        - /{{.SandboxName}}/{{.MepName}}/rni
        {{- else }}
        - /{{.SandboxName}}/rni
        {{- end }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .HttpsOnly }}
    {{- if .IsMepService }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{.SandboxName}}/{{.MepName}}/rni(/|$)(.*)$ /rni/$2 break;
    {{- else }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/{{.SandboxName}}/rni(/|$)(.*)$ /rni/$2 break;
    {{- end }}
    {{- if .AuthEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://$http_host/auth/v1/authenticate?svc=meep-rnis&sbox={{.SandboxName}}&mep={{.MepName}}
    {{- end }}
  labels: {}
  tls:

prometheus:
  monitor:
    enabled: true
    port: 9000
    interval: 10s
    additionalLabels: {}
    relabelings: []
    scrapeTimeout: 5s
    
codecov:
  enabled: false
  location: "<WORKDIR>/codecov/meep-rnis"

meepOrigin: core
